In [1]:
import numpy as np

In [2]:
scores=np.array([[85,90,78],
                 [92,88,95],
                 [76,95,85],
                 [90,85,92],
                 [88,76,89]])

In [9]:
# 1. Calculate the mean score of each subject (across all students)
subject_means = np.mean(scores, axis=0)
print("Mean score of each subject:", subject_means)


Mean score of each subject: [86.2 86.8 87.8]


In [10]:
# 2. Find the median score of each student (across all subjects)

student_medians = np.median(scores, axis=1)
print("Median score of each student:", student_medians)


Median score of each student: [85. 92. 85. 90. 88.]


In [11]:
# 3. Extract the scores of the student with the highest total score

highest_total_index = np.argmax(np.sum(scores, axis=1))
highest_scores = scores[highest_total_index]
print("Scores of the student with the highest total score:", highest_scores)


Scores of the student with the highest total score: [92 88 95]


In [12]:
# 4. Find the minimum and maximum scores in each subject

subject_mins = np.min(scores, axis=0)
subject_maxs = np.max(scores, axis=0)
print("Minimum score in each subject:", subject_mins)
print("Maximum score in each subject:", subject_maxs)


Minimum score in each subject: [76 76 78]
Maximum score in each subject: [92 95 95]


In [13]:
# 5. Reshape the array to have shape (3, 5)

scores_reshaped = np.transpose(scores)  # Transpose the array to switch rows and columns
print("Reshaped array:\n", scores_reshaped)


Reshaped array:
 [[85 92 76 90 88]
 [90 88 95 85 76]
 [78 95 85 92 89]]


In [14]:
# 6. Sort the scores of each subject in ascending order

sorted_scores = np.sort(scores_reshaped, axis=1)  # Sort along each row (subject)
print("Sorted scores:\n", sorted_scores)

Sorted scores:
 [[76 85 88 90 92]
 [76 85 88 90 95]
 [78 85 89 92 95]]
